services:
  firecrawl:
    image: ghcr.io/mendableai/firecrawl-mcp-server:latest
    environment:
      - PORT=8080
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
    ports: 
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - mcp-network
    labels:
      - "mcp-hub.service=firecrawl"
      - "mcp-hub.type=web-scraping"
      - "mcp-hub.description=Web scraping and content extraction"
