name: Debug GitHub Actions Environment

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Debug environment
        run: |
          chmod +x scripts/debug-github-actions.sh
          ./scripts/debug-github-actions.sh
